### PR TITLE
Reduce the unnecessary mutex

### PR DESCRIPTION
**Pull request by 1Feng**
The job_available_mutex will unlock after calling the
condition_variable::wait, and lock after it return. It means queue_mutex is unnecessary.

change:
1. reduce the unnecessary mutex
2. avoid dead-lock in job_available_var.wait's predicate, remove the call of JobsRemaining

### CODE REVIEW

**Comment by nbsdx** [comment]
`next_job` deadlocks in your code if the queue is empty, and you're waiting on a new job. `ThreadPool::AddJob` locks `queue_mutex`, but it can't because it's been lock already in `ThreadPool::next_job`.

**Comment by nbsdx** [comment]
I don't see the potential deadlock that you see in my code. Could you clarify? The additional `job_available_mutex` is needed because the `queue_mutex` is unlocked in the middle of `next_job`.

**Comment by 1Feng** [comment]
1. in my  pull request , when `job_available_var.wait`  calling, the `condition_variable::wait`  function will unlock the `queue_mutex` . and when current thread was notified, the `condition_variable::wait`   funciton will lock the `queue_mutex` . So no deadlocks for `ThreadPool::AddJob` . Is it right?http://www.cplusplus.com/reference/condition_variable/condition_variable/wait/
2. the "avoid dead-lock" in commit message means: After my pull request, removing the `job_available_mutex` , It make a deadlocks in  `job_available_var.wait()` ; Because when `wait()`  was notified, it will lock the `queue_mutex`  again( in my pull request), then check the predicate `JobsRemaining()) || bailout` (your code). But `JobsRemaining`  require the queue_mutex, so it will make a deadlock.  So I just call the queue.size() instead.

See https://github.com/nbsdx/ThreadPool/pull/3/commits . I reduce the mutex in the first commit, then it cause a deadlock. So I fix it in the second commit. Both make up this pull request.

I am sorry, my english is poor.

**Comment by nbsdx** [comment]
Ah, I understand. From here `next_job` can be simplified further by removing the `if( queue.empty() )`, and replacing it with just the wait: 

``` c++
std::function<void(void)> next_job() {
    std::function<void(void)> res;
    std::unique_lock<std::mutex> job_lock( queue_mutex );

    job_available_var.wait( job_lock, [this]{ queue.size() || bailout; } );

    // Get job from the queue
    if( !bailout ) {
        res = queue.front();
        queue.pop_front();
    }
    else { // If we're bailing out, 'inject' a job into the queue to keep jobs_left accurate.
        res = []{};
        ++jobs_left;
    }
    return res;
}
```

which is effectively 

``` c++
std::function<void(void)> next_job() {
    // ...
    while( !(queue.size() || bailout) )
        wait( job_lock );
    // ...
}
```

If the queue is empty, then it will wait, otherwise it will just pass over the wait. 

I didn't know that `condition_variable::wait` released the lock on the mutex; the API that I was looking at didn't mention that. Thanks!

**Comment by stfx** [comment]
> I didn't know that `condition_variable::wait` released the lock on the mutex; the API that I was looking at didn't mention that. Thanks!

Then shouldn't the same be done in `WaitAll` as well?

**Comment by 1Feng** [comment]
Yes, it seems well.
btw, U can see my new PR, maybe better.

**Pull request merged**
